name: gnn-experiments
channels:
  - defaults
  - conda-forge
  - pytorch
  - pyg

dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - scikit-learn
  - networkx
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-geometric
  - pip:
      - torch-geometric
